# Use an official OpenJDK runtime with Java 17 as the base image
FROM openjdk:17.0.1-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the build context to the container
COPY target/tap-entities-0.0.1-SNAPSHOT.jar entities.jar

# Expose the port your Spring Boot app runs on
EXPOSE 8080

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "entities.jar"]
